# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика1\SHA1window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SHA1(object):
    def setupUi(self, SHA1):
        SHA1.setObjectName("SHA1")
        SHA1.resize(987, 572)
        self.centralwidget = QtWidgets.QWidget(SHA1)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 3, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 0, 1, 2)
        SHA1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SHA1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 26))
        self.menubar.setObjectName("menubar")
        SHA1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SHA1)
        self.statusbar.setObjectName("statusbar")
        SHA1.setStatusBar(self.statusbar)

        self.retranslateUi(SHA1)
        QtCore.QMetaObject.connectSlotsByName(SHA1)

    def retranslateUi(self, SHA1):
        _translate = QtCore.QCoreApplication.translate
        SHA1.setWindowTitle(_translate("SHA1", "SHA-1"))
        self.label.setText(_translate("SHA1", "Введите текст:"))
        self.pushButton_2.setText(_translate("SHA1", "Вычислить из файла"))
        self.pushButton.setText(_translate("SHA1", "Вычислить"))
        self.pushButton_3.setText(_translate("SHA1", "Очистить"))
